"""
document_intelligence_custom.py
================================
Demonstrates the full lifecycle of custom Document Intelligence models:

  1. Custom extraction models:
       - Custom neural: recommended for varied/unstructured layouts
       - Custom template: for fixed-layout forms (precise bounding boxes)
     Workflow: label data in Document Intelligence Studio →
               build model → train → test → evaluate

  2. Composed model:
       - Combine multiple custom models (e.g., invoice_modelA + invoice_modelB)
         so a single API call routes to the best-matching component model
       - Useful when you have multiple form variants

  3. Testing a custom model:
       - Analyze documents using your trained model ID
       - Extract custom fields with confidence scores
       - Handle multi-page and multi-document results

AI-102 Exam Skills Mapped:
  - Implement a custom document intelligence model
  - Train, test, and publish a custom document intelligence model
  - Create a composed document intelligence model

How to prepare training data (before running this script):
  1. Collect 5–50 sample documents (recommended: 10+)
  2. Upload them to Azure Blob Storage
  3. Open Document Intelligence Studio: https://documentintelligence.ai.azure.com/
  4. Create a new "Custom extraction" project
  5. Label fields in each document
  6. Train the model from Studio OR use build_document_model() below

Required environment variables (see .env.sample):
  AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT - https://<resource>.cognitiveservices.azure.com/
  AZURE_DOCUMENT_INTELLIGENCE_KEY      - API key
  AZURE_STORAGE_CONNECTION_STR         - Storage account with training data
  AZURE_TRAINING_CONTAINER_SAS_URL     - SAS URL for the blob container with labeled data
  AZURE_CUSTOM_MODEL_ID                - (optional) Existing custom model ID to test
  AZURE_CUSTOM_MODEL_ID_2              - (optional) Second custom model ID for compose demo

Package: azure-ai-documentintelligence>=1.0.0
"""

import json
import os
import time
from dotenv import load_dotenv
from azure.core.credentials import AzureKeyCredential
from azure.core.exceptions import HttpResponseError
from azure.ai.documentintelligence import (
    DocumentIntelligenceClient,
    DocumentIntelligenceAdministrationClient,
)
from azure.ai.documentintelligence.models import (
    # Training
    BuildDocumentModelRequest,
    DocumentBuildMode,
    AzureBlobContentSource,
    # Compose
    ComposeDocumentModelRequest,
    ComponentDocumentModelDetails,
    # Analysis
    AnalyzeDocumentRequest,
    AnalyzeResult,
)

load_dotenv()

ENDPOINT = os.environ["AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT"]
KEY = os.environ["AZURE_DOCUMENT_INTELLIGENCE_KEY"]
TRAINING_SAS_URL = os.getenv("AZURE_TRAINING_CONTAINER_SAS_URL", "")
CUSTOM_MODEL_ID = os.getenv("AZURE_CUSTOM_MODEL_ID", "my-custom-model")
CUSTOM_MODEL_ID_2 = os.getenv("AZURE_CUSTOM_MODEL_ID_2", "my-custom-model-2")
COMPOSED_MODEL_ID = os.getenv("AZURE_COMPOSED_MODEL_ID", "my-composed-model")

analysis_client = DocumentIntelligenceClient(
    endpoint=ENDPOINT, credential=AzureKeyCredential(KEY)
)
admin_client = DocumentIntelligenceAdministrationClient(
    endpoint=ENDPOINT, credential=AzureKeyCredential(KEY)
)


# ---------------------------------------------------------------------------
# 1. Build (train) a custom model
# ---------------------------------------------------------------------------
def build_custom_model(
    model_id: str,
    sas_url: str,
    build_mode: str = "neural",
    description: str = "AI-102 demo custom model",
) -> dict:
    """
    Train a custom extraction model from labeled data in Azure Blob Storage.

    build_mode options:
      - 'neural'   : Cross-page, form variation-tolerant (recommended for most cases)
      - 'template' : Fixed-layout forms; uses exact field locations; faster inference

    The SAS URL must point to a blob container that contains:
      - Document files (PDF, JPEG, PNG, TIFF, BMP)
      - labels.json (generated by Document Intelligence Studio)
      - ocr.json files (auto-generated)

    Training typically takes 1–10 minutes depending on dataset size.
    """
    if not sas_url:
        print("  AZURE_TRAINING_CONTAINER_SAS_URL not set — skipping actual training.")
        print("  To train, provide a SAS URL to a container with labeled documents.")
        print(f"  Model ID that would be created: '{model_id}'")
        return {}

    print(f"\nBuilding custom model '{model_id}' (mode: {build_mode})...")
    print(f"  Training data: {sas_url[:60]}...")

    try:
        poller = admin_client.begin_build_document_model(
            build_request=BuildDocumentModelRequest(
                model_id=model_id,
                description=description,
                build_mode=DocumentBuildMode(build_mode),
                azure_blob_source=AzureBlobContentSource(
                    container_url=sas_url,
                    prefix=None,   # Optional: folder prefix within the container
                ),
                # tags: optional key-value metadata
                tags={"project": "ai102-demo", "environment": "dev"},
            )
        )

        print("  Training in progress (polling every 10 seconds)...")
        result = poller.result()

        # Build result contains the trained model details
        print(f"\n  Model '{result.model_id}' trained successfully!")
        print(f"  Created     : {result.created_on}")
        print(f"  Description : {result.description}")
        print(f"  Build mode  : {build_mode}")

        if result.doc_types:
            for doc_type_name, doc_type in result.doc_types.items():
                print(f"\n  Document type: '{doc_type_name}'")
                print(f"    Fields ({len(doc_type.field_schema or {})}):")
                for field_name, field_schema in (doc_type.field_schema or {}).items():
                    field_type = field_schema.get("type", "string")
                    confidence = (doc_type.field_confidence or {}).get(field_name, 0)
                    print(f"      - {field_name:<25} type={field_type:<15} confidence={confidence:.2f}")

        return {"model_id": result.model_id, "status": "succeeded"}

    except HttpResponseError as e:
        print(f"  Training failed: {e.message}")
        return {"model_id": model_id, "status": "failed", "error": e.message}


# ---------------------------------------------------------------------------
# 2. Get model details and evaluate
# ---------------------------------------------------------------------------
def get_model_details(model_id: str):
    """
    Retrieve detailed information about a trained model, including:
      - Document types it recognizes
      - Fields it can extract, with expected types
      - Average field confidence (proxy for model quality)
    """
    print(f"\n{'='*60}")
    print(f" Model Details: '{model_id}'")
    print(f"{'='*60}")

    try:
        model = admin_client.get_document_model(model_id)
        print(f"  Model ID    : {model.model_id}")
        print(f"  Description : {model.description or 'N/A'}")
        print(f"  Created     : {model.created_on}")
        print(f"  Tags        : {model.tags}")

        if not model.doc_types:
            print("  No document types defined (model may be a compose wrapper).")
            return

        for doc_type_name, doc_type in model.doc_types.items():
            print(f"\n  Document type: '{doc_type_name}'")
            print(f"    Build mode: {getattr(doc_type, 'build_mode', 'N/A')}")
            print(f"    Fields:")
            for field_name, schema in (doc_type.field_schema or {}).items():
                confidence = (doc_type.field_confidence or {}).get(field_name, 0)
                examples = schema.get("examples", [])
                example_str = f" (e.g. {examples[0]!r})" if examples else ""
                print(
                    f"      {field_name:<25} "
                    f"type={schema.get('type','str'):<15} "
                    f"confidence={confidence:.2f}{example_str}"
                )

    except HttpResponseError as e:
        print(f"  Error: {e.message}")


# ---------------------------------------------------------------------------
# 3. Test a custom model
# ---------------------------------------------------------------------------
def test_custom_model(model_id: str, document_url: str):
    """
    Analyze a document using a trained custom model.

    The result structure is identical to prebuilt models but uses YOUR
    field names as defined during labeling.
    """
    print(f"\n{'='*60}")
    print(f" Testing Custom Model: '{model_id}'")
    print(f"{'='*60}")
    print(f"  Document: {document_url}")

    try:
        poller = analysis_client.begin_analyze_document(
            model_id=model_id,
            analyze_request=AnalyzeDocumentRequest(url_source=document_url),
        )
        result: AnalyzeResult = poller.result()

        print(f"\n  Pages: {len(result.pages or [])}")
        print(f"  Documents found: {len(result.documents or [])}")

        for doc_idx, document in enumerate(result.documents or []):
            doc_type = document.doc_type
            confidence = document.confidence
            print(f"\n  Document {doc_idx + 1}:")
            print(f"    Doc type   : {doc_type}")
            print(f"    Confidence : {confidence:.3f}")

            # Custom-labeled fields
            print(f"    Fields ({len(document.fields or {})}):")
            for field_name, field in (document.fields or {}).items():
                field_value = field.get("content") or str(field.get("value", "N/A"))
                field_confidence = field.get("confidence", 0)
                print(
                    f"      {field_name:<30} "
                    f"value='{str(field_value)[:50]}' "
                    f"confidence={field_confidence:.3f}"
                )

    except HttpResponseError as e:
        if e.status_code == 404:
            print(f"  Model '{model_id}' not found. Train a model first.")
        else:
            print(f"  Error: {e.message}")


# ---------------------------------------------------------------------------
# 4. Create a composed model
# ---------------------------------------------------------------------------
def compose_models(
    component_model_ids: list[str],
    composed_model_id: str,
    description: str = "Composed model combining multiple custom models",
):
    """
    A composed model routes each document to the best-matching component model.

    Use cases:
      - Multiple invoice templates (supplier A, supplier B)
      - Multiple form variants (English form + French form)
      - Multiple document types handled by one API endpoint

    Requirements:
      - All component models must be custom models (not prebuilt)
      - Maximum 100 component models per composed model
      - Each component model must have the same API version

    The 'classify' step in composed models selects the best component
    based on document similarity scoring.
    """
    print(f"\n{'='*60}")
    print(f" Composing Models → '{composed_model_id}'")
    print(f"{'='*60}")
    print(f"  Components: {component_model_ids}")

    if not all(m for m in component_model_ids):
        print("  Skipping: all component model IDs must be set.")
        print("  Set AZURE_CUSTOM_MODEL_ID and AZURE_CUSTOM_MODEL_ID_2 in .env")
        return

    try:
        # Verify all component models exist
        for model_id in component_model_ids:
            model = admin_client.get_document_model(model_id)
            print(f"  Component '{model.model_id}': OK")

        # Compose
        poller = admin_client.begin_compose_document_model(
            compose_request=ComposeDocumentModelRequest(
                model_id=composed_model_id,
                description=description,
                component_models=[
                    ComponentDocumentModelDetails(model_id=mid)
                    for mid in component_model_ids
                ],
                tags={"type": "composed", "project": "ai102-demo"},
            )
        )

        result = poller.result()
        print(f"\n  Composed model '{result.model_id}' created!")
        print(f"  Component doc types:")
        for doc_type_name in (result.doc_types or {}):
            print(f"    - {doc_type_name}")

    except HttpResponseError as e:
        if e.status_code == 404:
            print(f"  One or more component models not found: {e.message}")
        else:
            print(f"  Error composing models: {e.message}")


# ---------------------------------------------------------------------------
# 5. Copy a model to another resource
# ---------------------------------------------------------------------------
def copy_model_to_resource(source_model_id: str, target_endpoint: str, target_key: str):
    """
    Copy a model to another Azure Document Intelligence resource.
    Useful for promoting models from dev → staging → production.

    Steps:
      1. Get a copy authorization from the TARGET resource
      2. Initiate the copy from the SOURCE resource using the authorization
    """
    print(f"\n{'='*60}")
    print(f" Copy Model: '{source_model_id}' → {target_endpoint}")
    print(f"{'='*60}")

    try:
        # Step 1: Authorize the copy in the target resource
        target_admin = DocumentIntelligenceAdministrationClient(
            endpoint=target_endpoint,
            credential=AzureKeyCredential(target_key),
        )
        copy_auth = target_admin.authorize_model_copy(
            authorize_copy_request={"modelId": f"{source_model_id}-copy"}
        )
        print(f"  Copy authorization obtained. Target model: {copy_auth.model_id}")

        # Step 2: Initiate copy from source resource
        poller = admin_client.begin_copy_document_model_to(
            model_id=source_model_id,
            copy_to_request=copy_auth,
        )
        result = poller.result()
        print(f"  Model copied successfully! Target model ID: {result.model_id}")

    except HttpResponseError as e:
        print(f"  Copy error: {e.message}")


# ---------------------------------------------------------------------------
# 6. Delete a model (cleanup)
# ---------------------------------------------------------------------------
def delete_model(model_id: str):
    """
    Delete a custom or composed model. This is irreversible.
    Use when retiring old models or managing quota.
    """
    print(f"\nDeleting model '{model_id}'...")
    try:
        admin_client.delete_document_model(model_id)
        print(f"  Model '{model_id}' deleted.")
    except HttpResponseError as e:
        if e.status_code == 404:
            print(f"  Model '{model_id}' not found (already deleted?).")
        else:
            print(f"  Error: {e.message}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    print("Azure Document Intelligence — Custom Model Lifecycle Demo")
    print(f"Endpoint: {ENDPOINT}")

    try:
        # 1. Show current model inventory
        print("\n--- Existing Models ---")
        models = list(admin_client.list_models())
        print(f"Total models: {len(models)}")
        for m in models[:10]:
            print(f"  {m.model_id}")

        # 2. Train a custom model (only if SAS URL is provided)
        if TRAINING_SAS_URL:
            build_custom_model(
                model_id=CUSTOM_MODEL_ID,
                sas_url=TRAINING_SAS_URL,
                build_mode="neural",
                description="AI-102 demo: custom invoice model",
            )
        else:
            print("\n[SKIP] Training: AZURE_TRAINING_CONTAINER_SAS_URL not set.")

        # 3. Get details of the custom model
        get_model_details(CUSTOM_MODEL_ID)

        # 4. Test the model on a sample document
        # Use the sample invoice from the prebuilt demo
        SAMPLE_DOC_URL = (
            "https://raw.githubusercontent.com/Azure-Samples/"
            "cognitive-services-REST-api-samples/master/curl/form-recognizer/sample-invoice.pdf"
        )
        test_custom_model(CUSTOM_MODEL_ID, SAMPLE_DOC_URL)

        # 5. Compose two custom models into one
        compose_models(
            component_model_ids=[CUSTOM_MODEL_ID, CUSTOM_MODEL_ID_2],
            composed_model_id=COMPOSED_MODEL_ID,
        )

        # 6. Test the composed model
        get_model_details(COMPOSED_MODEL_ID)

        print("\nCustom model lifecycle demo complete!")
        print("\nExam Tips:")
        print("  - Custom neural models handle layout variations better than template")
        print("  - Need 5+ labeled samples minimum; 10+ recommended for good accuracy")
        print("  - Confidence scores < 0.8 suggest the field needs more training samples")
        print("  - Composed models classify the document type automatically")
        print("  - Models can be copied between regions for DR or deployment pipelines")

    except KeyError as e:
        print(f"Missing environment variable: {e}")
        raise
    except HttpResponseError as e:
        print(f"API error [{e.status_code}]: {e.message}")
        raise


if __name__ == "__main__":
    main()
